# Generated by Django 4.2 on 2023-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('toEmail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=240, verbose_name='Subject')),
            ],
        ),
    ]
